version: '3.9'

services:
  backend:
    build:
      context: ./backend
    ports:
      - "3000:3000"
    volumes:
      - ./backend/cache:/backend/cache
      - ./backend/scripts:/backend/scripts
      - /Users/aidancorrell/repos/my_cool_dbt_repo/my_cool_dbt_project:/backend/dbt_project
    environment:
      - RUST_LOG=info

  frontend:
    build:
      context: ./frontend
    ports:
      - "3001:3001"
