version: '3.9'

services:
  backend:
    build:
      context: ./backend
    ports:
      - "3000:3000"
    volumes:
      - ./backend/cache:/backend/cache
      - ./backend/scripts:/backend/scripts
      - /absolute/path/to/your/dbt_project:/backend/dbt_project # be sure to update this path with your dbt project path
    environment:
      - RUST_LOG=info

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "8080:80" # The container's port 80 is mapped to port 8080
    restart: always # Restart the container if it crashes

  # for local dev
  # frontend:
  #   build:
  #     context: ./frontend
  # ports:
  #   - "3001:3001"
  # environment:
  #   - PORT=3001
  # volumes:
  #   - ./frontend:/frontend  # Mount the local frontend folder for live reloading
