version: "3.8"

services:
  backend:
    build:
      context: ./backend
    ports:
      - "3000:3000"
    volumes:
      - ./backend/cache:/backend/cache
    depends_on:
      - scheduler

  scheduler:
    build:
      context: ./backend
      dockerfile: Dockerfile
    volumes:
      - ./backend/cache:/backend/cache
    command: ["cron", "-f"]

  frontend:
    build:
      context: ./frontend
    ports:
      - "3001:3001" # Expose the front-end service
    depends_on:
      - backend
